#!/usr/bin/env python3
"""Real-runtime regression for the mob.gold overwrite defect.

The fixture includes a normal level-60 NPC.  Its converted wallet is nonzero and
is generated by the production ``convertMob`` path, rather than by the prototype
cash line.  The test uses a deliberately steep, valid test-only curve so the
bounded 75..125% converter rolls cannot make two independent A/B runs overlap:
setting 5 is neutral, while setting 10 is a 1000x player-favouring inverse.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import signal
import subprocess
import tempfile
import time

from test_flatfile_combat_journey import (
    MudClient,
    available_ports,
    build_flatfile_server,
    create_character,
    generate_certificate,
    make_fixture,
    make_overlord,
    reconnect_character,
)

ROOT = pathlib.Path(__file__).resolve().parents[2]
INSPECTOR = ROOT / "bin/tests/coin-death-inspector"
TARGET_VNUM = 22801
TARGET_KEY = "gold_target"
NO_MONEY_KEY = "no_money_target"
MINIMUM_KEY = "minimum_coin_target"
TEST_CURVE = "0.001"


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def set_properties(path: pathlib.Path, values: dict[str, str]) -> None:
    text = path.read_text()
    for key, value in values.items():
        marker = f"{key}="
        matches = [line for line in text.splitlines() if line.startswith(marker)]
        require(len(matches) == 1, f"missing or duplicate shipped property {key}")
        text = text.replace(f"{matches[0]}\n", f"{key}={value}\n", 1)
    path.write_text(text)


def add_gold_target(run_root: pathlib.Path) -> None:
    """Add one ordinary, coin-valued level-60 NPC to the mini world."""
    mobile_path = run_root / "areas_mini/mini.mob"
    mobiles = mobile_path.read_text()
    target = """#22801
gold_target~
a gold-bearing regression target~
A gold-bearing regression target waits here for the mob.gold test.
~
~
10 0 0 0 0 0 0 0 S
PH 0 0 -1
60 0 -250 1000d1+50000 10d10+200
123.456.789.321 0
8 8 0
#22802
no_money_target _nomoney_~
a no-money regression target~
A no-money regression target must never retain a wallet.
~
~
10 0 0 0 0 0 0 0 S
PH 0 0 -1
60 0 -250 1000d1+50000 10d10+200
123.456.789.321 0
8 8 0
#22803
minimum_coin_target~
a minimum-coin regression target~
A minimum-coin regression target must retain one copper.
~
~
10 0 0 0 0 0 0 0 S
PH 0 0 -1
1 0 -250 1d1+1 1d1+1
0.0.0.0 0
8 8 0
"""
    for vnum in ("#22801\n", "#22802\n", "#22803\n"):
        require(vnum not in mobiles, f"gold target already present in fixture: {vnum.strip()}")
    require(mobiles.count("$~") == 1, "mini mobile terminator changed")
    mobile_path.write_text(mobiles.replace("$~", target + "$~", 1))

    zone_path = run_root / "areas_mini/mini.zon"
    zone = zone_path.read_text()
    reset = (
        "M 0 22801 1 22800 100 0 0 0 * deterministic gold target\n"
        "M 0 22802 1 22800 100 0 0 0 * deterministic no-money target\n"
        "M 0 22803 1 22800 100 0 0 0 * deterministic minimum target\n"
    )
    require("deterministic gold target" not in zone, "gold reset already present in fixture")
    require(zone.count("\nS\n") == 1, "mini zone terminator changed")
    zone_path.write_text(zone.replace("\nS\n", "\n" + reset + "S\n", 1))


def make_gold_fixture(run_root: pathlib.Path) -> pathlib.Path:
    make_fixture(run_root)
    add_gold_target(run_root)
    set_properties(run_root / "lib/duris.properties", {
        "difficulty.curve.10": TEST_CURVE,
    })
    (run_root / "logs/log").mkdir(parents=True)
    (run_root / "logs/log/.gitignore").write_text("*\n!.gitignore\n")
    (run_root / "journals/critical").mkdir(parents=True, mode=0o700)
    generate_certificate(run_root)
    return run_root / "server.out"


def environment(state_root: pathlib.Path, run_root: pathlib.Path,
                tls_port: int, websocket_port: int) -> dict[str, str]:
    env = {
        "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
        "ENVIRONMENT": "local",
        "PERSISTENCE_MODE": "flatfile-primary",
        "FLATFILE_STATE_DIR": str(state_root),
        "CRITICAL_COMMAND_JOURNAL_DIR": str(run_root / "journals/critical"),
        "LISTEN_ADDRESS": "127.0.0.1",
        "DURIS_TLS_PORT": str(tls_port),
        "DURIS_WEBSOCKET_LISTEN_ADDRESS": "127.0.0.1",
        "DURIS_WEBSOCKET_PORT": str(websocket_port),
        "REDIS": "FALSE",
        "DURIS_NEVENT_TRACE_PLAYER": "1",
        "CHAOS_MUD": "FALSE",
    }
    if os.environ.get("LD_LIBRARY_PATH"):
        env["LD_LIBRARY_PATH"] = os.environ["LD_LIBRARY_PATH"]
    return env


def boot(binary: pathlib.Path, state_root: pathlib.Path, run_root: pathlib.Path,
         output_path: pathlib.Path, plain_port: int):
    tls_port, websocket_port = plain_port + 1, plain_port + 2
    output = output_path.open("a", encoding="utf-8")
    process = subprocess.Popen(
        [str(binary), "--minimal", "-s", "-d", str(run_root), str(plain_port)],
        cwd=run_root,
        env=environment(state_root, run_root, tls_port, websocket_port),
        stdout=output,
        stderr=subprocess.STDOUT,
        text=True,
    )
    deadline = time.monotonic() + 120
    while time.monotonic() < deadline:
        output.flush()
        text = output_path.read_text(errors="replace")
        if "Entering game loop." in text:
            return process, output
        if process.poll() is not None:
            raise AssertionError(f"server exited during boot ({process.returncode}):\n{text[-8000:]}")
        time.sleep(0.1)
    raise AssertionError("gold regression server did not reach Entering game loop")


def stop(process, output) -> None:
    if process.poll() is None:
        process.send_signal(signal.SIGTERM)
        try:
            process.wait(timeout=30)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=10)
    output.flush()
    output.close()
    require(process.returncode == 0, f"server shutdown returned {process.returncode}")


def drain(client: MudClient, seconds: float = 0.8) -> None:
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        client._receive()
        time.sleep(0.05)


def dismiss_pager(client: MudClient) -> None:
    if b"[Return to continue" not in bytes(client.pending):
        return
    client.expect("[Return to continue", timeout=10)
    client.send("q")
    deadline = time.monotonic() + 15
    while time.monotonic() < deadline:
        if b"<>" in bytes(client.pending) or b"Pos:" in bytes(client.pending):
            return
        client._receive()
        time.sleep(0.05)
    raise AssertionError("stat pager did not return to the gameplay prompt")


def stat_target_money(client: MudClient, key: str = TARGET_KEY,
                      require_nonempty: bool = True) -> tuple[int, int, int, int]:
    # Consume the post-login prompt before issuing the real command.
    client.expect_any(("<>", "Pos:"), timeout=30)
    start = len(client.transcript)
    client.send(f"stat char {key}")
    client.expect("Pcoins:", timeout=30)
    drain(client)
    text = bytes(client.transcript[start:]).decode("utf-8", errors="replace")
    match = re.search(
        r"Pcoins:\s*(\d+).*?Gcoins:\s*(\d+).*?Scoins:\s*(\d+).*?Ccoins:\s*(\d+)",
        text,
        re.DOTALL,
    )
    if match is None:
        raise AssertionError(f"could not parse target wallet:\n{text[-8000:]}")
    values = tuple(int(match.group(index)) for index in range(1, 5))
    result = (values[0], values[1], values[2], values[3])
    require(not require_nonempty or any(result),
            f"target wallet unexpectedly empty: {result}")
    dismiss_pager(client)
    return result


def run_case(binary: pathlib.Path, setting: int) -> tuple[int, int, int, int]:
    with tempfile.TemporaryDirectory(prefix=f"gold-fix-state-{setting}-") as state_tmp, \
            tempfile.TemporaryDirectory(prefix=f"gold-fix-run-{setting}-") as run_tmp:
        state_root, run_root = pathlib.Path(state_tmp), pathlib.Path(run_tmp)
        state_root.chmod(0o700)
        (state_root / "domains").mkdir(mode=0o700)
        subprocess.run([str(INSPECTOR), str(state_root), "seed-combat"], check=True, timeout=30)
        output_path = make_gold_fixture(run_root)
        set_properties(run_root / "lib/duris.properties", {
            "difficulty.dial.mob.gold": str(setting),
        })
        plain, _, _ = available_ports()
        process, output = boot(binary, state_root, run_root, output_path, plain)
        client: MudClient | None = None
        try:
            client = MudClient(plain)
            create_character(client)
            client.send("save")
            client.expect("Save complete for Taverek.", timeout=30)
            client.send("quit")
            client.expect("ACCOUNT MENU", timeout=30)
            client.send("0")
            client.close()
            client = None
            stop(process, output)
            # stat char needs a god.
            make_overlord(state_root, "Taverek")
            process, output = boot(binary, state_root, run_root, output_path, plain)
            client = reconnect_character(plain)
            values = stat_target_money(client)
            no_money = stat_target_money(client, NO_MONEY_KEY, require_nonempty=False)
            minimum = stat_target_money(client, MINIMUM_KEY)
            require(no_money == (0, 0, 0, 0),
                    f"_nomoney_ target retained a wallet at setting {setting}: {no_money}")
            require(minimum[:3] == (0, 0, 0) and minimum[3] >= 1,
                    f"minimum-coin target lost its copper or gained a higher denomination "
                    f"at setting {setting}: {minimum}")
            client.send("quit")
            client.expect("ACCOUNT MENU", timeout=30)
            client.send("0")
            client.close()
            client = None
            stop(process, output)
            print(f"setting={setting} target_wallet={values} no_money_wallet={no_money} "
                  f"minimum_wallet={minimum}", flush=True)
            return values
        finally:
            if client is not None:
                client.close()
            if process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
            output.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--server", type=pathlib.Path,
                        help="flat-file server binary (default: build one)")
    args = parser.parse_args()
    subprocess.run(["python3", "tests/async/test_flatfile_player_repository.py",
                    "--build-inspector", str(INSPECTOR)], cwd=ROOT, check=True, timeout=180)
    if args.server:
        require(args.server.is_file() and os.access(args.server, os.X_OK),
                f"server binary is not executable: {args.server}")
        compare(args.server.resolve())
        return
    (ROOT / "bin/tests").mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="gold-dial-build-", dir=ROOT / "bin/tests") as build:
        compare(build_flatfile_server(pathlib.Path(build)))


def compare(binary: pathlib.Path) -> None:
    neutral = run_case(binary, 5)
    hard = run_case(binary, 10)
    neutral_total = neutral[0] * 1000 + neutral[1] * 100 + neutral[2] * 10 + neutral[3]
    hard_total = hard[0] * 1000 + hard[1] * 100 + hard[2] * 10 + hard[3]
    # The normal level-60 converter's four rolls are bounded to 75..125.  The
    # test-only 1000x multiplier therefore leaves a very wide, deterministic
    # gap even though the two server instances use independent entropy.
    require(hard_total > neutral_total * 50,
            f"mob.gold was not applied after conversion: neutral={neutral}, hard={hard}")
    print("mob.gold runtime regression passed: normal coin-valued NPC scales after convertMob")


if __name__ == "__main__":
    main()
