#!/usr/bin/env python3
"""make_trg builds world.trg from the areas' trg/<area>.trg sources and refuses a
malformed one with its file and line, which fails make world."""
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[2]
GOOD = "* a comment\n#100 M\nT SPEECH hello\nsay Hi, $n.\n~\nS\n"
MARKER = "* generated by make_trg from areas/trg; edit those files\n"
MALFORMED = {
    "#200 O\nT DEATH\nsay ow\nS\n": "trg/bad.trg:4: a trigger is not ended by ~",
    "#200 O\nT DEATH\nsay ow\n~\n": "trg/bad.trg:4: a record is not ended by S",
    "#200\nT DEATH\n": "trg/bad.trg:1: expected a #<vnum> <M|O|R> record header",
    "#200 X\n": "trg/bad.trg:1: expected a #<vnum> <M|O|R> record header",
    "#200 R\nsay ow\n": "trg/bad.trg:2: expected T, S or a * comment",
    "#~\n": 'trg/bad.trg:1: "#~" ends the combined file; a source may not hold it',
}

with tempfile.TemporaryDirectory(prefix="duris-make-trg-") as scratch:
    tool = Path(scratch) / "make_trg"
    subprocess.run(["gcc", "-Wall", "-Wextra", "-Werror", "-o", str(tool),
                    str(ROOT / "areas/src/trg/make_trg.c")], check=True)
    run = Path(scratch) / "areas"
    (run / "trg").mkdir(parents=True)
    (run / "trg/good.trg").write_text(GOOD)

    # An area without a source is skipped; the file always ends with "#~".
    (run / "AREA").write_text("* comment\ngood *1\nplain *2\n")
    subprocess.run([str(tool)], cwd=run, check=True, stdout=subprocess.DEVNULL)
    assert (run / "tworld.trg").read_text() == MARKER + GOOD + "#~\n"
    (run / "trg/good.trg").unlink()
    subprocess.run([str(tool)], cwd=run, check=True, stdout=subprocess.DEVNULL)
    assert (run / "tworld.trg").read_text() == MARKER + "#~\n"

    # A source without a final newline does not run into the next one.
    (run / "AREA").write_text("good *1\nnext *2\n")
    (run / "trg/good.trg").write_text(GOOD.rstrip("\n"))
    (run / "trg/next.trg").write_text(GOOD)
    subprocess.run([str(tool)], cwd=run, check=True, stdout=subprocess.DEVNULL)
    assert (run / "tworld.trg").read_text() == MARKER + GOOD + GOOD + "#~\n"

    # A world.trg that make_trg did not write and that holds a record is the only copy
    # of those records: refuse to replace it. Its own output and a "#~"-only file pass.
    for header in ("#22800 R", "# 22800 R"):
        hand_written = f"* my triggers\n{header}\nT ENTER\necho hi\n~\nS\n#~\n"
        (run / "world.trg").write_text(hand_written)
        result = subprocess.run([str(tool)], cwd=run, stdout=subprocess.DEVNULL,
                                stderr=subprocess.PIPE, text=True)
        assert result.returncode != 0, header
        assert result.stderr == ('error: world.trg was not written by make_trg; move its records, '
                                 'without the "#~" line, into trg/<area>.trg\n'), result.stderr
        assert (run / "world.trg").read_text() == hand_written
    for previous in ((run / "tworld.trg").read_text(), "#~\n"):
        (run / "world.trg").write_text(previous)
        subprocess.run([str(tool)], cwd=run, check=True, stdout=subprocess.DEVNULL)
    (run / "world.trg").unlink()

    (run / "AREA").write_text("bad *1\n")
    for source, error in MALFORMED.items():
        (run / "trg/bad.trg").write_text(source)
        result = subprocess.run([str(tool)], cwd=run, stdout=subprocess.DEVNULL,
                                stderr=subprocess.PIPE, text=True)
        assert result.returncode != 0, source
        assert result.stderr == f"error: {error}\n", (source, result.stderr)

print("make_trg builds world.trg and refuses a malformed trigger source")
